### ISSUE TITLE
[language] The endif statement

### ISSUE THREAD

**Issue by vanillajonathan** [felicien-brochu/selflessheroes#10]
Many other languages does not have any `endif` statement. Python relies on indention for scoping.
Hence can do:
```py
if w == switch:
    step(w)
```
It would be pretty cool if the language used by _Selfless Heroes_ was the same or very close to a very popular programming language (such as Python or JavaScript) used in the real world so the skills and knowledge would directly translate.

**Comment by felicien-brochu** [comment]
The language won't change, unless a whole new version of the game is done.
