### ISSUE TITLE
[language] Support for comments

### ISSUE THREAD

**Issue by vanillajonathan** [felicien-brochu/selflessheroes#11]
There could be support for comments in the code.

Maybe with `#` as is used in Python, Perl, Ruby, shell script and also supported in PHP.
Or maybe with `//` and/or `/* comment */` as is used in JavaScript, TypeScript, Java, PHP, C#, etc.

**Comment by felicien-brochu** [comment]
The language won't change, unless a whole new version of the game is done, with other levels etc.
