### ISSUE TITLE
Configure sponsor on GitHub

### ISSUE THREAD

**Issue by vanillajonathan** [felicien-brochu/selflessheroes#12]
Configure selflessheroes on GitHub to display a sponsor button.

https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

You use the `custom` field in the FUNDING.yml file to provide a link to PayPal and Steam.

**Comment by felicien-brochu** [comment]
Thanks for the advice! I did not even know that github had this feature. It's done.
