### ISSUE TITLE
Add shortcut keys

### ISSUE THREAD

**Issue by vanillajonathan** [felicien-brochu/selflessheroes#5]
Add <kbd>F5</kbd> to run.
Add <kbd>Shift</kbd>+<kbd>F5</kbd> to stop running.
Add <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F5</kbd> to restart.
Add <kbd>F10</kbd> to step over.

Add a hotkey to toggle between the code designer and the code editor.

**Comment by felicien-brochu** [comment]
Hi @vanillajonathan !
Some keymaps already exist:
Play/Pause: <kbd>ctrl</kbd>+<kbd>space</kbd>
Pause: <kbd>Pause</kbd>
Step: <kbd>ctrl</kbd>+<kbd>return</kbd>
Undo: <kbd>ctrl</kbd>+<kbd>z</kbd>
Redo: <kbd>ctrl</kbd>+<kbd>y</kbd> OR <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>z</kbd>

I won't use <kbd>F*</kbd> keys for technical reasons. But I think about adding keymaps to switch between editors and to restart.

**Comment by vanillajonathan** [comment]
These hotkeys could be better documented as they're not very obvious or discoverable.

Also there could be hotkeys to increase/decrease the execution speed, example <kbd>+</kbd> and <kbd>-</kbd>.

**Comment by felicien-brochu** [comment]
Yeah I know. I will add the shortcuts to the tooltip when you hover the buttons with the cursor.
Speed change is also planned.

**Comment by vanillajonathan** [comment]
You might also want to consider implementing a place where all the shortcuts are listed in one place.

Example:
![image](https://user-images.githubusercontent.com/10222521/80800047-c55a0880-8ba8-11ea-92d2-484f26247ed1.png)

**Comment by felicien-brochu** [comment]
Here is the list of keymaps implemented in v1.2.7

'ctrl+z': undo
'ctrl+y': redo
'ctrl+shift+z': redo
'ctrl+space': togglePlayPause
'ctrl+enter': stepOnce
'pause': pause
'ctrl+backspace': stop
'home': stop
'alt+right': increaseSpeed
'alt+left': decreaseSpeed
'ctrl+e': switchEditor

**Comment by vanillajonathan** [comment]
It would be great if this information would be available in summarized form in-game too.

**Comment by felicien-brochu** [comment]
Like I said it's in the tooltips. I think that's enough.
