### ISSUE TITLE
Remember the execution speed setting

### ISSUE THREAD

**Issue by vanillajonathan** [felicien-brochu/selflessheroes#6]
I am not sure if this is by design and there might be a rationale for why the execution speed should be reset.

But you might want to consider whether the game should remember the execution speed setting, because right now it does get reset to the default speed every time you finish a level and proceed to the next.

**Comment by felicien-brochu** [comment]
I think it's good practice to begin debugging at slow speed. Some players would let the speed to 99x all the time. And it's the default behaviour on all games of the genre.
