### ISSUE TITLE
[language] Colon before space

### ISSUE THREAD

**Issue by vanillajonathan** [felicien-brochu/selflessheroes#7]
If you were to drop the space before the colon (`if myitem == cauldron :` into `if myitem == cauldron:`) the syntax would more similar to that of Python.

It would be pretty cool if the language used by _Selfless Heroes_ was the same or very close to a very popular programming language (such as Python or JavaScript) used in the real world so the skills and knowledge would directly translate.

**Comment by felicien-brochu** [comment]
The language won't change, unless a whole new version of the game is done.

**Comment by felicien-brochu** [comment]
The language won't change, unless a whole new version of the game is done.
