### ISSUE TITLE
[language] The boolean operators

### ISSUE THREAD

**Issue by vanillajonathan** [felicien-brochu/selflessheroes#9]
The `&&` and `||` doesn't tell much to non-programmers, first-time programmers, to kids or people with a background in mathematics.

[Python](https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not) uses the `and` and `or` (and `not`) operators. Perhaps these operators would be more intuitive and easier to grasp.

[PHP](https://www.php.net/manual/en/language.operators.logical.php) lets you use both the  `&&` and `||` and also the `and` and `or` operators.

**Comment by felicien-brochu** [comment]
The language won't change, unless a whole new version of the game is done.
